# -*- coding: utf-8 -*-
"""data-generation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBWB65J3Yfzw7SGfmM-S9karY3ESUFYa
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

x = np.random.randn(100,2)
print(x)

y = 2+0.6*x[:,0]+0.8*x[:,1]
print(y.shape)
y1 = np.array(y).reshape([-1,1])
print(y1.shape)
plt.scatter(x[:,0], x[:,1])

#add y1 to matrix x (2 columns)
dt = np.append(x,y1,axis=1) #appending column y1 to x; axis is appending along an axis, so this is the y axis (1) x being 0 
# and it makes a n by 2 matrix a n by 3 matrix adding a column 
df = pd.DataFrame(dt,columns = ['x1','x2','y1'])
df.head()