# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/159b7mV0RieA-LFtU26T13GOBzSugJZMn
"""

#data generation
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt 
x = np.random.randn(100,1)
y = 8 + 0.6*x[:,0] + 0.4*x[:,1]
y1 = np.array(y).reshape([-1,1])
dt = np.append(x,y1,axis = 1)
df = pd.DataFrame(dt, columns = ["x1","x2","y1"])

from sklearn.cluster import KMeans 
inertias = [] 

for i in range(1,11):
    kmeans = KMeans(n_clusters=i, init = 'k-means++')
    kmeans.fit(x)
    inertias.append(kmeans.inertia_)

plt.plot(range(1,11), inertias, marker='o')
plt.title('Elbow method')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.show()

kmeans = KMeans(n_clusters = 2)
kmeans.fit(x)
plt.scatter(x[:,0],x[:,1] , c = kmeans.labels_)
plt.show()