# -*- coding: utf-8 -*-
"""linear-regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lmhko43K4MBjrGe1f_NH1uVFCyV6EuKa
"""

from sklearn import datasets

diabetes = datasets.load_diabetes()

diabetes

print(diabetes.DESCR)

print(diabetes.feature_names)

x = diabetes.data
y = diabetes.target

x.shape, y.shape

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

x_train.shape, x_test.shape

from sklearn import linear_model #linear regression model

from sklearn.metrics import mean_squared_error, r2_score #to compute performance

model = linear_model.LinearRegression()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

#perfomance
print(model.coef_)
print(model.intercept_)
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test,y_pred))

y_test

y_pred

import seaborn as sns
sns.scatterplot(y_test, y_pred)